export declare const category: string;
export declare const container: string;
export declare const pagination: string;
export declare const quantity: string;
export declare const selectItemOnPage: string;
export declare const selects: string;
export declare const selectSortBy: string;
export declare const sortTitle: string;
export declare const title: string;
