export declare const content: string;
export declare const hpTitle: string;
export declare const img: string;
export declare const link: string;
export declare const quantity: string;
export declare const section: string;
export declare const sectionTitle: string;
export declare const title: string;
export declare const wrapp: string;
